#!/command/with-contenv /bin/bash
# SPDX-FileCopyrightText: 2023-2025 Daniel Wolf <nephatrine@gmail.com>
# SPDX-License-Identifier: ISC

# shellcheck shell=bash
# shellcheck disable=SC1091

export HOME=/mnt/config/home
export DRONE_LOG_FILE=${DRONE_LOG_FILE:-"/mnt/config/log/drone-docker-runner.log"}
export DRONE_RPC_PROTO=${DRONE_RPC_PROTO:-"http"}
export DRONE_RUNNER_NAME=${DRONE_RUNNER_NAME:-"$(hostname)"}
export DRONE_RUNNER_CAPACITY=${DRONE_RUNNER_CAPACITY:-1}
export DRONE_RUNNER_OS=${DRONE_RUNNER_OS:-"linux"}

if [[ "$(/bin/uname -m)" == "aarch64" ]]; then
  export DRONE_RUNNER_ARCH=${DRONE_RUNNER_ARCH:-"arm64"}
elif [[ "$(/bin/uname -m)" == "armv7l" || "$(/bin/uname -m)" == "armv8l" ]]; then
  export DRONE_RUNNER_ARCH=${DRONE_RUNNER_ARCH:-"arm"}
elif [[ "$(/bin/uname -m)" == "x86_64" ]]; then
  export DRONE_RUNNER_ARCH=${DRONE_RUNNER_ARCH:-"amd64"}
else
  export DRONE_RUNNER_ARCH=${DRONE_RUNNER_ARCH:-"$(uname -m)"}
fi

cd /mnt/config/home || exit 1

if [[ ! -d /mnt/config/etc ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/etc
fi
if [[ ! -d /mnt/config/etc && ! -f /mnt/config/etc/drone-runner-config ]]; then
  /bin/echo "#!/bin/sh" | /command/s6-setuidgid guardian /usr/bin/tee /mnt/config/etc/drone-runner-config
  /bin/echo "#export DRONE_RPC_SECRET=" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/etc/drone-runner-config
  /bin/echo "#export DRONE_RPC_PROTO=http" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/etc/drone-runner-config
  /bin/echo "#export DRONE_RPC_HOST=example.net" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/etc/drone-runner-config
  /bin/echo "#export DRONE_RUNNER_NAME=$(hostname)" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/etc/drone-runner-config
  /bin/echo "#export DRONE_RUNNER_CAPACITY=1" | /command/s6-setuidgid guardian /usr/bin/tee -a /mnt/config/etc/drone-runner-config
  /command/s6-setuidgid guardian /bin/chmod +x /mnt/config/etc/drone-runner-config
fi
if [[ -f /mnt/config/etc/drone-runner-config ]]; then
  . /mnt/config/etc/drone-runner-config
fi

if [[ ! -d /mnt/config/log ]]; then
  /command/s6-setuidgid guardian /bin/mkdir -p /mnt/config/log
fi
if [[ ! -f "${DRONE_LOG_FILE}" ]]; then
  /command/s6-setuidgid guardian /bin/touch "${DRONE_LOG_FILE}"
else
  /bin/chown guardian:users "${DRONE_LOG_FILE}"
fi

if [[ -n "${DRONE_RPC_SECRET}" && -n "${DRONE_RPC_HOST}" ]]; then
  exec /usr/bin/drone-runner-docker
else
  /bin/echo "** no SECRET or HOST given **"
  /bin/sleep 300
  exit 0
fi
